// Purchase module constants and mock data

export const purchaseData = {
  // Purchase orders
  orders: [
    {
      id: 'PO-2025-001',
      supplierName: 'Cotton Mills Ltd',
      supplierContact: 'John Miller',
      supplierEmail: 'john@cottonmills.com',
      orderDate: '2025-09-18',
      expectedDate: '2025-10-02',
      receivedDate: null,
      status: 'Pending',
      priority: 'High',
      totalAmount: 25000.0,
      items: [
        {
          id: 'ITEM-001',
          productId: 'FAB-001',
          productName: 'Cotton Premium',
          quantity: 500,
          unitPrice: 12.0,
          totalPrice: 6000.0,
          receivedQty: 0,
          specification: '100% Cotton, 60" width, 150 GSM',
        },
        {
          id: 'ITEM-002',
          productId: 'FAB-005',
          productName: 'Cotton Standard',
          quantity: 800,
          unitPrice: 9.5,
          totalPrice: 7600.0,
          receivedQty: 0,
          specification: '100% Cotton, 58" width, 140 GSM',
        },
      ],
      paymentStatus: 'Not Required',
      paymentMethod: 'Net 30',
      discount: 0,
      taxAmount: 1250.0,
      shippingCost: 300.0,
      notes: 'Rush order for upcoming production schedule',
    },
    {
      id: 'PO-2025-002',
      supplierName: 'Silk Traders Inc',
      supplierContact: 'Maria Rodriguez',
      supplierEmail: 'maria@silktraders.com',
      orderDate: '2025-09-20',
      expectedDate: '2025-10-08',
      receivedDate: '2025-09-25',
      status: 'Received',
      priority: 'Medium',
      totalAmount: 18750.0,
      items: [
        {
          id: 'ITEM-003',
          productId: 'FAB-002',
          productName: 'Silk Blend Luxury',
          quantity: 300,
          unitPrice: 34.0,
          totalPrice: 10200.0,
          receivedQty: 300,
          specification: '70% Silk, 30% Cotton, 45" width, 120 GSM',
        },
      ],
      paymentStatus: 'Paid',
      paymentMethod: 'Bank Transfer',
      discount: 500.0,
      taxAmount: 937.5,
      shippingCost: 250.0,
      notes: 'Quality checked and approved',
    },
    {
      id: 'PO-2025-003',
      supplierName: 'Natural Fibers Ltd',
      supplierContact: 'David Chen',
      supplierEmail: 'david@naturalfibers.com',
      orderDate: '2025-09-22',
      expectedDate: '2025-10-10',
      receivedDate: null,
      status: 'Confirmed',
      priority: 'Low',
      totalAmount: 12600.0,
      items: [
        {
          id: 'ITEM-004',
          productId: 'FAB-004',
          productName: 'Linen Natural',
          quantity: 200,
          unitPrice: 21.5,
          totalPrice: 4300.0,
          receivedQty: 0,
          specification: '100% Linen, 52" width, 180 GSM',
        },
      ],
      paymentStatus: 'Pending',
      paymentMethod: 'Net 45',
      discount: 200.0,
      taxAmount: 630.0,
      shippingCost: 180.0,
      notes: 'Standard delivery acceptable',
    },
  ],

  // Suppliers
  suppliers: [
    {
      id: 'SUP-001',
      name: 'Cotton Mills Ltd',
      type: 'Cotton Supplier',
      contactPerson: 'John Miller',
      email: 'john@cottonmills.com',
      phone: '+1-555-0123',
      address: '123 Industrial Ave, Cotton City, TX 75001',
      paymentTerms: 'Net 30',
      creditLimit: 100000,
      currentBalance: 25000.0,
      rating: 4.5,
      lastOrderDate: '2025-09-18',
      totalOrders: 45,
      categories: ['Cotton', 'Raw Materials'],
      documents: ['Tax Certificate', 'Quality Certificate', 'Insurance'],
      performance: {
        onTimeDelivery: 92,
        qualityRating: 4.5,
        priceCompetitiveness: 4.2,
      },
    },
    {
      id: 'SUP-002',
      name: 'Silk Traders Inc',
      type: 'Silk Supplier',
      contactPerson: 'Maria Rodriguez',
      email: 'maria@silktraders.com',
      phone: '+1-555-0124',
      address: '456 Silk Road, Fashion District, NY 10001',
      paymentTerms: 'Net 15',
      creditLimit: 75000,
      currentBalance: 0,
      rating: 4.8,
      lastOrderDate: '2025-09-20',
      totalOrders: 32,
      categories: ['Silk', 'Premium Materials'],
      documents: ['Tax Certificate', 'Quality Certificate'],
      performance: {
        onTimeDelivery: 96,
        qualityRating: 4.8,
        priceCompetitiveness: 3.9,
      },
    },
    {
      id: 'SUP-003',
      name: 'Synthetic Fabrics Co',
      type: 'Synthetic Supplier',
      contactPerson: 'Robert Kim',
      email: 'robert@syntheticfabrics.com',
      phone: '+1-555-0125',
      address: '789 Tech Blvd, Innovation Park, CA 94043',
      paymentTerms: 'Net 30',
      creditLimit: 60000,
      currentBalance: 15000.0,
      rating: 4.2,
      lastOrderDate: '2025-09-15',
      totalOrders: 28,
      categories: ['Synthetic', 'Blended Materials'],
      documents: ['Tax Certificate', 'Environmental Compliance'],
      performance: {
        onTimeDelivery: 88,
        qualityRating: 4.2,
        priceCompetitiveness: 4.6,
      },
    },
    {
      id: 'SUP-004',
      name: 'Natural Fibers Ltd',
      type: 'Natural Fiber Supplier',
      contactPerson: 'David Chen',
      email: 'david@naturalfibers.com',
      phone: '+1-555-0126',
      address: '321 Organic Way, Green Valley, OR 97401',
      paymentTerms: 'Net 45',
      creditLimit: 80000,
      currentBalance: 12600.0,
      rating: 4.3,
      lastOrderDate: '2025-09-22',
      totalOrders: 38,
      categories: ['Linen', 'Organic Materials'],
      documents: [
        'Organic Certificate',
        'Tax Certificate',
        'Quality Certificate',
      ],
      performance: {
        onTimeDelivery: 90,
        qualityRating: 4.3,
        priceCompetitiveness: 4.1,
      },
    },
  ],

  // Purchase requests/requisitions
  requisitions: [
    {
      id: 'PR-2025-001',
      requestedBy: 'Production Manager',
      department: 'Production',
      requestDate: '2025-09-25',
      requiredDate: '2025-10-15',
      status: 'Pending Approval',
      priority: 'Medium',
      items: [
        {
          productName: 'Cotton Premium',
          quantity: 300,
          estimatedPrice: 12.5,
          estimatedTotal: 3750.0,
          justification: 'Stock running low, needed for Order SO-2025-004',
        },
      ],
      totalEstimated: 3750.0,
      approvedBy: null,
      approvedDate: null,
      notes: 'Urgent requirement for production schedule',
    },
    {
      id: 'PR-2025-002',
      requestedBy: 'Inventory Manager',
      department: 'Inventory',
      requestDate: '2025-09-24',
      requiredDate: '2025-10-20',
      status: 'Approved',
      priority: 'Low',
      items: [
        {
          productName: 'Polyester Blend',
          quantity: 500,
          estimatedPrice: 8.75,
          estimatedTotal: 4375.0,
          justification: 'Seasonal stock replenishment',
        },
      ],
      totalEstimated: 4375.0,
      approvedBy: 'Purchase Manager',
      approvedDate: '2025-09-25',
      notes: 'Standard replenishment order',
    },
  ],

  // Purchase performance data
  performance: {
    monthlySpend: [
      { month: 'Jan', amount: 85000, orders: 12 },
      { month: 'Feb', amount: 92000, orders: 15 },
      { month: 'Mar', amount: 78000, orders: 11 },
      { month: 'Apr', amount: 105000, orders: 18 },
      { month: 'May', amount: 98000, orders: 16 },
      { month: 'Jun', amount: 112000, orders: 20 },
      { month: 'Jul', amount: 89000, orders: 14 },
      { month: 'Aug', amount: 94000, orders: 17 },
      { month: 'Sep', amount: 87000, orders: 13 },
    ],
    topCategories: [
      { category: 'Cotton', amount: 320000, percentage: 35 },
      { category: 'Silk', amount: 240000, percentage: 26 },
      { category: 'Synthetic', amount: 180000, percentage: 20 },
      { category: 'Linen', amount: 120000, percentage: 13 },
      { category: 'Others', amount: 55000, percentage: 6 },
    ],
    supplierPerformance: [
      { supplier: 'Cotton Mills', orders: 45, onTime: 92, quality: 4.5 },
      { supplier: 'Silk Traders', orders: 32, onTime: 96, quality: 4.8 },
      { supplier: 'Synthetic Co', orders: 28, onTime: 88, quality: 4.2 },
      { supplier: 'Natural Fibers', orders: 38, onTime: 90, quality: 4.3 },
    ],
  },
};

// Status color mappings
export const purchaseStatusColors = {
  Draft: 'default',
  Pending: 'warning',
  Confirmed: 'info',
  'Partially Received': 'primary',
  Received: 'success',
  Cancelled: 'error',
  'On Hold': 'secondary',
};

export const paymentStatusColors = {
  'Not Required': 'default',
  Pending: 'warning',
  Paid: 'success',
  Overdue: 'error',
  Partial: 'info',
};

export const priorityColors = {
  Low: 'success',
  Medium: 'warning',
  High: 'error',
  Urgent: 'error',
};

export const requisitionStatusColors = {
  Draft: 'default',
  'Pending Approval': 'warning',
  Approved: 'success',
  Rejected: 'error',
  Converted: 'info',
};

// Chart configurations for purchase
export const purchaseChartConfig = {
  colors: {
    primary: '#1976d2',
    secondary: '#dc004e',
    success: '#4caf50',
    warning: '#ff9800',
    error: '#f44336',
    info: '#2196f3',
  },
  categoryColors: ['#1976d2', '#4caf50', '#ff9800', '#f44336', '#9c27b0'],
};
